
"error with : JA-A-25-12-01-00A-520A-A_UnarmouredSeat_Screws_CP_1.5_3"

"error with : JA-A-25-12-01-00A-520A-A_UnarmouredSeat_Nuts_CP_1.5_3"

"error with : JA-A-25-12-01-00A-520A-A_UnarmouredSeat_Screws_P_1.5_3"

"error with : JA-A-25-12-01-00A-520A-A_UnarmouredSeat_Nuts_P_1.5_3"

"error with : overhead"

"error with : push_btn197"

"error with : flip_base261"



for obj in geometry do if classof obj.material == Multimaterial do print obj.name
	
x1 = getclassinstances bitmapTexture 
for i = 1 to x1.count do print x1[i].bitmap

