" i = 1 , max Faces = 802 JA-A-25-71-21-00A-520A-A_RadomeFairingLowerInstalled_RH_1.2"
" i = 2 , max Faces = 2340 JA-A-93-77-01-00A-520A-A_IFF_MountingTray"
" i = 3 , max Faces = 2408 JA-A-93-21-05-00A-720A-A_WeatherRadomeBondingArea_1.5"
" i = 4 , max Faces = 3204 JA-A-25-71-21-00A-520A-A_RadomeFairingLowerInstalled_LH_1.2"
" i = 5 , max Faces = 3690 Fuselage_lower_WireCutter"
" i = 6 , max Faces = 7457 JA-A-93-21-05-00A-520A-A_WeatherRadome_1.2"
" i = 7 , max Faces = 10544 JA-A-93-12-01-06A-520A-B_FLIR_ThermalImager_1.4"
" i = 8 , max Faces = 10817 JA-A-43-42-21-00A-520A-A_Tray_2"
" i = 9 , max Faces = 11090 JA-A-43-42-21-00A-520A-A_Tray_1"
" i = 10 , max Faces = 11363 JA-A-43-21-03-00A-520A-A_VHF_FM_PIP_Tray"
" i = 11 , max Faces = 11473 JA-A-43-21-01-00A-520A-A_VHF_FM_Transceiver_Tray"
" i = 12 , max Faces = 11965 JA-A-34-55-03-01A-520A-A_ConnectorJ2_socket_1.2"
" i = 13 , max Faces = 12513 JA-A-34-11-02-00A-041A-A_RH_PITOT_PROBE_INSTALLED_1.3"
" i = 14 , max Faces = 13061 JA-A-34-11-02-00A-041A-A_LH_PITOT_PROBE_INSTALLED_1.3"
" i = 15 , max Faces = 17445 DoorwayNoseAvionicBay"
" i = 16 , max Faces = 25115 JA-A-25-71-20-00A-520A-A_RadomeFairingUpperInstalled_1.2"
" i = 17 , max Faces = 25185 ROPSAU"
" i = 18 , max Faces = 25615 JA-A-93-78-01-00A-520A-A_IFF_AntennaAdapterUnit"
" i = 19 , max Faces = 25870 JA-A-43-42-21-00A-520A-A_Transceiver_2"
" i = 20 , max Faces = 26125 JA-A-43-42-21-00A-520A-A_Transceiver_1"
" i = 21 , max Faces = 26229 JA-A-43-21-03-00A-520A-A_VHF_FM_PIP"
" i = 22 , max Faces = 26852 JA-A-43-21-01-00A-520A-A_VHF_FM_Transceiver"
" i = 23 , max Faces = 27389 JA-A-99-34-01-00A-520A-A_MLDSU_1.7_2"
" i = 24 , max Faces = 27926 JA-A-99-34-01-00A-520A-A_MLDSU_1.7_1"
" i = 25 , max Faces = 28639 JA-A-99-32-01-00A-520A-A_RSU_1.1_2"
" i = 26 , max Faces = 29352 JA-A-99-32-01-00A-520A-A_RSU_1.1_1"
" i = 27 , max Faces = 29445 JA-A-43-21-03-00A-520A-A_VHF_FM_PIP_Lever"
" i = 28 , max Faces = 29538 JA-A-43-42-21-00A-520A-A_Tray_1_LeverClosed"
" i = 29 , max Faces = 29631 JA-A-43-42-21-00A-520A-A_Tray_1_LeverOpened"
" i = 30 , max Faces = 29724 JA-A-43-42-21-00A-520A-A_Tray_2_LeverClosed"
" i = 31 , max Faces = 29817 JA-A-43-42-21-00A-520A-A_Tray_2_LeverOpened"
29817
#{29725..29817}
0
polyop.setFaceSelection $ #{803..2340}



	ChannelInfo.CopyChannel $ 3 3
	ChannelInfo.PasteChannel $ 3 1
	collapseStack $