/*##############################################################################
SugzTools Startup
Version 0.02
Script By Clément "Sugz" Plantec
plantec.clement@gmail.com
###############################################################################*/


if doesFileExist "$userScripts\SugzTools\Libs\SugzTools_Manager_Struct.ms" do fileIn "$userScripts\SugzTools\Libs\SugzTools_Manager_Struct.ms"
