-------------------------------------------------------------------------------
-- Felipe_StereoCam.mcr
-- MacroScripts File
-- By Philippe DASSONVILLE (dassonphil@gmail.com)
-- Max 2010 :  Install in : 3ds Max 2010\ui\macroscripts
-- Max 2013 :  Install in : 3ds Max 2013\macroscripts
-- 2014/04/15
-- V3
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------

macroScript StereoCam
category:"Felipe Scripts"
toolTip:"StereoCam"
buttonText:"StereoCam"
icon:#("Felipe Scripts",10)
silentErrors:true
autoUndoEnabled:true

pda_maxpath = symbolicPaths.getPathValue 9 + "\\Felipe_StereoCam_v32.mse"

include pda_maxpath









